In [ ]:
#pandas - is a python library used to organize clean and manipulate structured data
import pandas as pd

Requirement already satisfied: pandas in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.1)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting cufflinks
  Downloading cufflinks-0.17.3.tar.gz (81 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: openpyxl in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: six>=1.9.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cufflinks) (1.17.0)
Collecting colorlover>=0.2.1 (from cufflinks)
  Downloading colorlover-0.3.0-py3-none-any.whl.metadata (421 bytes)
Requirement already satisfied: setuptools>=34.4.1 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cufflinks) (82.0.1)
Requirement already satisfied: ipython>=5.3.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cufflinks) (9.11.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cufflinks) (8.1.8)
Requirement already satisfied: et-xmlfile in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: wcwidth in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.6.0)
Requirement already satisfied: comm>=0.1.3 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jedi>=0.18.2->ipython>=5.3.0->cufflinks) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\shres\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (0.2.3)
Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.5 MB 6.2 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/9.5 MB 6.6 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.5 MB 6.5 MB/s eta 0:00:01
   ---------------------- ----------------- 5.2/9.5 MB 6.4 MB/s eta 0:00:01
   ---------------------------- ----------- 6.8/9.5 MB 6.6 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.5 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 6.2 MB/s  0:00:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 5.0 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.9 MB 5.9 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/9.9 MB 7.1 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.9 MB 7.1 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.4 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.4 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.4 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.2 MB/s  0:00:01
Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.3 MB 6.3 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 4.9 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ------- -------------------------------- 1.3/7.2 MB 7.9 MB/s eta 0:00:01
   -------------- ------------------------- 2.6/7.2 MB 6.9 MB/s eta 0:00:01
   --------------------- ------------------ 3.9/7.2 MB 6.5 MB/s eta 0:00:01
   ----------------------- ---------------- 4.2/7.2 MB 5.8 MB/s eta 0:00:01
   ----------------------- ---------------- 4.2/7.2 MB 5.8 MB/s eta 0:00:01
   --------------------------- ------------ 5.0/7.2 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 4.5 MB/s  0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Building wheels for collected packages: cufflinks
  Building wheel for cufflinks (pyproject.toml): started
  Building wheel for cufflinks (pyproject.toml): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68888 sha256=2354422465d9eeccf5e74e9ae509729da1dd8c36c9da80f8d6402b854a11fa1d
  Stored in directory: c:\users\shres\appdata\local\pip\cache\wheels\e4\0d\21\3611484024347032ee330271868478a2c28877581eb01f9b79
Successfully built cufflinks
Installing collected packages: colorlover, pyparsing, pillow, narwhals, kiwisolver, fonttools, cycler, contourpy, plotly, matplotlib, seaborn, cufflinks

   --- ------------------------------------  1/12 [pyparsing]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ------ ---------------------------------  2/12 [pillow]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ---------- -----------------------------  3/12 [narwhals]
   ------------- --------------------------  4/12 [kiwisolver]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   ---------------- -----------------------  5/12 [fonttools]
   -------------------- -------------------  6/12 [cycler]
   ----------------------- ----------------  7/12 [contourpy]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   -------------------------- -------------  8/12 [plotly]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]
   ------------------------------ ---------  9/12 [matplotlib]

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\shres\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script plotly_get_chrome.exe is installed in 'c:\Users\shres\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Pandas has two main data structures:

Series: One-dimensional data, similar to a single column.

DataFrame: Two-dimensional data containing rows and columns, similar to an Excel table.

What is Nump py ?

NumPy stands for Numerical Python. It is used for numerical calculations and working with arrays.

In [3]:
import numpy as np

numbers = np.array([10, 20, 30, 40])
print (numbers)

[10 20 30 40]

In [4]:
#importing OS -module is used to interact with the computer’s operating system, folders, and files.
import os

print(os.getcwd())       # Shows the current folder
print(os.listdir())      # Shows files in the current folder

d:\AL ML Class\Python Class\Pandas_Practice
['pandas_data_manipulation.ipynb']

In [1]:
#importing Matplolib 

import matplotlib.pyplot as plt

In [3]:
#creating a Dataframe 

import pandas as pd 
 
data = {
    "Name": ["Maya", "Riya", "Sita", "Anita", "Nina"],
    "Age": [22, 25, 24, 28, None],
    "City": ["New York", "Boston", "New York", "Chicago", "Boston"],
    "Salary": [45000, 52000, 48000, 60000, 55000]
}

df = pd.DataFrame(data)

print (df)

    Name   Age      City  Salary
0   Maya  22.0  New York   45000
1   Riya  25.0    Boston   52000
2   Sita  24.0  New York   48000
3  Anita  28.0   Chicago   60000
4   Nina   NaN    Boston   55000

In [4]:
df.head() #head- display the first five rows by default

    Name   Age      City  Salary
0   Maya  22.0  New York   45000
1   Riya  25.0    Boston   52000
2   Sita  24.0  New York   48000
3  Anita  28.0   Chicago   60000
4   Nina   NaN    Boston   55000

In [5]:
df.head(3) #display the first three rows

   Name   Age      City  Salary
0  Maya  22.0  New York   45000
1  Riya  25.0    Boston   52000
2  Sita  24.0  New York   48000

In [ ]:
df.tail() #display the last five rows by default

    Name   Age      City  Salary
0   Maya  22.0  New York   45000
1   Riya  25.0    Boston   52000
2   Sita  24.0  New York   48000
3  Anita  28.0   Chicago   60000
4   Nina   NaN    Boston   55000

In [ ]:
print(df.dtypes) #shows the data type of every column

Name          str
Age       float64
City          str
Salary      int64
dtype: object

In [ ]:
print(df.index) #display the row labels of the dataframe

In [9]:
print(df.columns) #displays all columns names

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [10]:
print(df.shape)  #shows the number of rows and columns

(5, 4)

In [11]:
df.describe() #provides statistical information about numerical columns

         Age        Salary
count   4.00      5.000000
mean   24.75  52000.000000
std     2.50   5873.670062
min    22.00  45000.000000
25%    23.50  48000.000000
50%    24.50  52000.000000
75%    25.75  55000.000000
max    28.00  60000.000000

In [12]:
#filtering data - filtering select rows that meet a condition 

df[df["Salary"] > 50000]

    Name   Age     City  Salary
1   Riya  25.0   Boston   52000
3  Anita  28.0  Chicago   60000
4   Nina   NaN   Boston   55000

In [13]:
df[(df["Salary"] > 5000) & (df["City"] == "Boston")]

   Name   Age    City  Salary
1  Riya  25.0  Boston   52000
4  Nina   NaN  Boston   55000

What is Series?

A series is one dimensional labeled collection. It is similar to one column in a table

In [14]:
scores = pd.Series([85, 90, 78, 92])

print(scores)

0    85
1    90
2    78
3    92
dtype: int64

In [15]:
scores = pd.Series(
    [85, 90, 72],
    index=["Maya", "Sadi", "Rita"]
)

print(scores)

Maya    85
Sadi    90
Rita    72
dtype: int64

What is random.seed?

A random seed makes randomly generated values repeatable

In [16]:
import numpy as np 

np.random.seed(42)

numbers = np.random.randint(1, 100, 5)

print(numbers)

[52 93 15 72 61]

In [17]:
#reset_index () - replaces the existing index with the default index 

filtered_df = df[df["Salary"] > 50000]

filtered_df = filtered_df.reset_index()

In [18]:
#multiindex - allows a Dataframe to have more than one index level 

multi_df = df.set_index(["City", "Name"])

print(multi_df)

                 Age  Salary
City     Name
New York Maya   22.0   45000
Boston   Riya   25.0   52000
New York Sita   24.0   48000
Chicago  Anita  28.0   60000
Boston   Nina    NaN   55000

In [19]:
#finding missing values 

df.isna()

#counting missing values 

df.isna() and sum()

#dropna- remove rows or column containing missing values 

#remove rows with missing values 

df.dropna()

df.dropna(axis=1) #remove columns with missing values

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [21]:
#fillna()-fills missing values instead of deleting them 

df["Age"] = df["Age"].fillna(0)

#fill with the mean 

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [22]:
#fill with meadian 

df["Age"] = df["Age"].fillna(df["Age"].median())

Group By - Combine rows with the same category and perfoms calculation on them

In [23]:
#avergae salary by city 

df.groupby("City")["Salary"].mean()

City
Boston      53500.0
Chicago     60000.0
New York    46500.0
Name: Salary, dtype: float64

In [24]:
#multiple calulation 
df.groupby("City")["Salary"].agg(["count","mean","min","max"])

          count     mean    min    max
City
Boston        2  53500.0  52000  55000
Chicago       1  60000.0  60000  60000
New York      2  46500.0  45000  48000

In [25]:
#Groups using multiple columns 

df.groupby(["City","Age"])["Salary"].mean()

City      Age
Boston    0.0     55000.0
          25.0    52000.0
Chicago   28.0    60000.0
New York  22.0    45000.0
          24.0    48000.0
Name: Salary, dtype: float64

In [26]:
#groupby() with describe()

df.groupby("City")["Salary"].describe()

,count,mean,std,min,25%,50%,75%,max
City,,,,,,,,
Boston,2.0,53500.0,2121.320344,52000.0,52750.0,53500.0,54250.0,55000.0
Chicago,1.0,60000.0,NaN,60000.0,60000.0,60000.0,60000.0,60000.0
New York,2.0,46500.0,2121.320344,45000.0,45750.0,46500.0,47250.0,48000.0

In [ ]:
#Transpose - Transpose changes rows into columns and columns into rows

df.transpose()

df.T #shortform 

df.groupby("City")["Salary"].describe().T

In [27]:
#combining dataframes

employee = pd.DataFrame({
    "Employee_ID":[1, 2, 3],
    "Name":["Maya","Riya","Sita"]
    })
departments = pd.DataFrame({
    "EmployeeID":[1,2,4],
    "Department": ["Marketing", "Finance","IT"]
})

In [ ]:
#merging two dataframes

merged_df = pd.merge(
    employees,
    departments,
    on="EmployeeID"
)

print(merged_df)

In [ ]:
#innerjoin- Returns only matching records.
pd.merge(
    employees,
    departments,
    on="EmployeeID",
    how="inner"
)

In [ ]:
#leftjoin- Returns every row from the left DataFrame and matching rows from the right DataFrame.
pd.merge(
    employees,
    departments,
    on="EmployeeID",
    how="left"
)

In [ ]:
#right join-Returns every row from the right DataFrame and matching rows from the left DataFrame

pd.merge(
    employees,
    departments,
    on="EmployeeID",
    how="right"
)

In [1]:
#concatenation 
#concat()- Concatenation places DataFrames together.

df1 = pd.DataFrame({
    "Name": ["Maya", "Riya"],
    "Age": [22, 25]
})

df2 = pd.DataFrame({
    "Name": ["Sita", "Anita"],
    "Age": [24, 28]
})

combined = pd.concat(
    [df1, df2],
    ignore_index=True
)

print(combined)

NameError: name 'pd' is not defined